name: Update TRMNL Security Deadlines

# When to run this automation
on:
  schedule:
    # Run every 3 hours for more frequent updates
    - cron: '0 */3 * * *'
  
  # Allow manual triggering from GitHub website
  workflow_dispatch:

jobs:
  update-deadlines:
    runs-on: ubuntu-latest
    
    steps:
      # Get your code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Set up Python environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      # Install required Python packages
      - name: Install dependencies
        run: |
          pip install requests pyyaml python-dateutil pytz
      
      # Generate JSON data for TRMNL polling
      - name: Generate conference data JSON
        run: |
          python generate_data.py
          echo "Generated data file:"
          ls -la trmnl-data.json
          echo "Data preview:"
          head -20 trmnl-data.json
      
      # Deploy to GitHub Pages for TRMNL polling
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          keep_files: false
          
      - name: Show polling URL
        run: |
          echo "🎉 Your TRMNL polling URL is ready:"
          echo "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/trmnl-data.json"
          echo ""
          echo "📝 Next steps:"
          echo "1. Go to your TRMNL plugin settings"
          echo "2. Change Strategy from 'Webhook' to 'Polling'"
          echo "3. Set Polling URL to the URL above"
          echo "4. Set refresh interval (recommended: 30 minutes)"