name: Update TRMNL Security Deadlines

# When to run this automation
on:
  schedule:
    # Run every 3 hours for more frequent updates
    - cron: '0 */3 * * *'
  
  # Allow manual triggering from GitHub website
  workflow_dispatch:

# Add permissions for GitHub Pages deployment
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-deadlines:
    runs-on: ubuntu-latest
    
    steps:
      # Get your code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Set up Python environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      # Install required Python packages
      - name: Install dependencies
        run: |
          pip install requests pyyaml python-dateutil pytz
      
      # Generate JSON data for TRMNL polling
      - name: Generate conference data JSON
        run: |
          echo "Current time: $(date)"
          python generate_data.py
          echo "Generated data file:"
          ls -la trmnl-data.json
          echo "Timestamp in generated file:"
          grep "last_updated" trmnl-data.json
          echo "Data preview:"
          head -20 trmnl-data.json
      
      # Deploy to GitHub Pages for TRMNL polling
      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      # Deploy to GitHub Pages for TRMNL polling  
      - name: Prepare deployment directory
        run: |
          mkdir -p deploy
          cp trmnl-data.json deploy/
          echo "Files to deploy:"
          ls -la deploy/
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          publish_branch: gh-pages
          keep_files: false
          
      - name: Show polling URL
        run: |
          echo "🎉 Deployment complete!"
          echo "Your TRMNL polling URL is:"
          echo "https://alixabbasi.github.io/TRMNL-Sec-Deadlines/trmnl-data.json"
          echo ""
          echo "Wait 2-3 minutes for GitHub Pages to update, then check the URL."
          echo "The timestamp should show: $(date '+%b %d, %H:%M')"